### ISSUE TITLE
GetLoadStatus bug ?

### ISSUE THREAD

**Issue by Stuermer** [ericmandel/js9#48]
Hi,
when using the GetLoadStatus function, I get a JavaScript error 'id.split is not a function'.
(Line 17864 in js9.js)
After a bit of debugging it seems that
	    id0 = id.id.split('/').reverse()[0];
fixes it.
However, I've no experience in JavaScript, so I didn't create a PR etc. since I'm not sure if this is the 'correct' fix for the problem.

p.s. this happened after I updated from js9 version 2.0.1 to 2.1

**Comment by ericmandel** [comment]
What arg you passing to GetLoadStatus()? Maybe the image handle? The call wants the image id (text string):

<img width="382" alt="screen shot 2018-09-19 at 12 13 48 pm" src="https://user-images.githubusercontent.com/3028875/45766425-89f20c80-bc05-11e8-8b8e-292d3d97b0d5.png">

I see there was a bug fix made in November, and perhaps that broke how you were calling GetLoadStatus()? If so, I should make it backward compatible  .... let me know your calling sequence.

**Comment by Stuermer** [comment]
I'm sorry, you're right, I was not passing a string.
I'm using JS9 within a Wt project (https://www.webtoolkit.eu/wt) and I made an error when calling JavaScript commands from within C++.
The full JavaScript code I'm executing looked like this:
"var done = JS9.GetLoadStatus(o6rjdvv_JS9);var a1=done;Wt.emit('o6rjdvv','doneSignal',done);"
Changing it to 
"var done = JS9.GetLoadStatus('o6rjdvv_JS9');var a1=done;Wt.emit('o6rjdvv','doneSignal',done);"
solved the issue.

Not sure why it worked in the previous versions - but glad you found my error.
Thanks.

**Comment by ericmandel** [comment]
Oh, I see, good that it was easily fixed! I'll look into why the behavior changed with invalid input ... maybe the return needs to be more forgiving.

Since everything is working as you want, I'll close this issue, regardless of whether I make a change ...
